name: SimpleSpectatorMode
version: 1.0.0-SNAPSHOT
main: dev.em_3.simplespectatormode.SimpleSpectatorMode
description: A plugin that allows non-opped players to access a limited version of spectator mode
author: EM_3
api-version: '1.20.6'